### ISSUE TITLE
Подгон временной плана работы и посторенние диаграммы Ганта

### ISSUE THREAD

**Issue by protuberancer** [b1art/tablereader#5]

**Comment by wwarmss** [comment]
почти все этапы работы находятся в процессе, ввиду чего они поставлены на loop до момента их полного выполнения 

если есть предварительные сроки окончания заданий - просьба указать комментарием к заданию

**Comment by protuberancer** [comment]
> почти все этапы работы находятся в процессе, ввиду чего они поставлены на loop до момента их полного выполнения
> 
> если есть предварительные сроки окончания заданий - просьба указать комментарием к заданию

Определить предварительные сроки окончания заданий - твоя задача. 
Можешь опираться на презентацию - https://cs.petrsu.ru/studies/se/SE2023.pdf
